version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    expose:
      - "8081"
  nginx:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
  fava:
    build: ./fava
    volumes:
      - /tmp/real.beancount:/real.beancount
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - BEANCOUNT_FILE=/real.beancount