version: '3.7'
services:
  web:
    build: .
    ports:
      - "9050:9050"
    expose:
      - "9050"
    volumes:
      - type: volume
        source: gainstrack
        target: /app/db

#  nginx:
#    image: "nginx"
#    volumes:
#      - ./nginx/nginx-docker.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "8080:8080"
volumes:
  gainstrack:
    external: true
