<template>
    <div>

        <template v-for="command in commands">
            <el-card class="box-card" :body-style="{ padding: '5px' }" shadow="always">
                <div @click="go(command)" :id="'add-'+command.title.toLowerCase()" style="cursor: pointer;">
                    <el-link><span class="el-icon-circle-plus-outline" ></span> {{command.title}}</el-link>
                    <el-divider></el-divider>
                    {{ command.description }}
                </div>
            </el-card>
            <br>
        </template>
    </div>

</template>

<script>
    import {Card, Link, Divider, DatePicker} from 'element-ui';
    import lang from 'element-ui/lib/locale/lang/en'
    import locale from 'element-ui/lib/locale'

    locale.use(lang);

    export default {
        name: 'Add',
        methods: {
            go(cmd) {
                this.$router.push({path: '/add/cmd', query: {cmd: cmd.prefix}});
            },
        },
        data() {
            return {
                commands: [
                    {prefix: 'open', title: 'Open Account', description: 'Open an account'},
                    {prefix: 'bal', title: 'Balance', description: 'Record a balance in an account'},
                    {prefix: 'unit', title: 'Unit', description: 'Record a balance of securities in a multi-asset account'},
                    {prefix: 'trade', title: 'Trade', description: 'Record a trade of securities in a multi-asset account'},
                    {prefix: 'tfr', title: 'Transfer', description: 'Perform a transfer from one account to another'},
                    {prefix: 'fund', title: 'Fund', description: 'Fund an account from a source'},
                    {prefix: 'earn', title: 'Earn', description: 'Record an income generated by yourself (e.g. salary)'},
                    {prefix: 'yield', title: 'Yield', description: 'Record an income generated by an asset you have (e.g. dividends)'}
                ],
            }
        },
        components: {
            'el-card': Card,
            'el-link': Link,
            'el-divider': Divider,
            'el-datepicker': DatePicker,
        }
    }
</script>

<style scoped>
    .clearfix:before,
    .clearfix:after {
        display: table;
        content: "";
    }
    .clearfix:after {
        clear: both
    }

    .body-style {
        padding: 0px;
    }

    .box-card {
        width: 480px;
    }

    .el-divider {
        margin: 0px;
    }
</style>