<template>
    <div>

        <div class="block">
            <span class="demonstration">P&L Explain Date Range: </span>
            <el-date-picker
                    v-model="selectedRange"
                    type="daterange"
                    align="right"
                    unlink-panels
                    range-separator="To"
                    start-placeholder="Start date"
                    end-placeholder="End date"
                    value-format="yyyy-MM-dd"
                    :picker-options="pickerOptions">
            </el-date-picker>
            <button @click="submit" :disabled="selectedRange==null">Go</button>
        </div>
        <div class="block" v-if="explains.length>0">
            P&L Explanat
            ion
<!--            Map("actual" -> actualPnl, "explained" -> explained, "unexplained" -> unexplained,-->
<!--            "newActivityPnl" -> newActivityPnl,-->
<!--            "totalEquity" -> totalEquity, "totalIncome" -> totalIncome, "totalExpense" -> totalExpense, "totalDeltaExplain" -> totalDeltaExplain-->
<!--            // , "delta" -> deltaExplain-->
<!--            )-->
            <table class="sortable">
                <tbody>
                <tr>
                    <td>Tenor</td>
                    <td class="description" v-for="explainData in explains"><span @click="onColumnClick(explainData)">{{ explainData.tenor}}</span></td>
                </tr>
                <tr>
                    <td>From Date</td>
                    <td class="datecell" v-for="explainData in explains">{{ explainData.fromDate}}</td>
                </tr>
                <tr>
                    <td>To Date</td>
                    <td class="datecell" v-for="explainData in explains">{{ explainData.toDate}}</td>
                </tr>
                <tr>
                    <td>
                        <el-tooltip class="item" effect="dark" content="P&L from positions as of from-date due to market price movements (excludes P&L from market movements of new trades done within the period)" placement="top-start">
                            <i class="el-icon-info"></i>
                        </el-tooltip>
                        Markets P&L
                    </td>
                    <td class="num" v-for="explainData in explains">{{ explainData.totalDeltaExplain.toFixed(2) }}</td>
                </tr>
<!--                <tr v-for="(ccy, ccyIndex) in explains[0].delta">-->
<!--                    <td>{{ ccy.assetId }}</td>-->
<!--                    <td class="num" v-for="explainData in explains">{{ explainData.delta[ccyIndex].explain.toFixed(2) }}</td>-->
<!--                </tr>-->
                <tr>
                    <td>Income</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.totalIncome.toFixed(2) }}</td>
                </tr>
                <tr>
                    <td>Expenses</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.totalExpense.toFixed(2) }}</td>
                </tr>
                <tr>
                    <td>Equity</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.totalEquity.toFixed(2) }}</td>
                </tr>
                <tr>
                    <td>                        <el-tooltip class="item" effect="dark" content="P&L generated by trades within the period, including both purchase at premium/discount and market price movements within the period" placement="top-start">
                        <i class="el-icon-info"></i>
                    </el-tooltip>
                        New Activity P&L</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.newActivityPnl.toFixed(2) }}</td>
                </tr>
                <tr>
                    <td>Explained P&L</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.explained.toFixed(2) }}</td>
                </tr>
                <tr>
                    <td>Actual P&L</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.actual.toFixed(2) }}</td>
                </tr>
                <tr>
                    <td>Unexplained P&L</td>
                    <td class="num" v-for="explainData in explains">{{ explainData.unexplained.toFixed(2) }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
    import axios from 'axios';
    import {DatePicker, Tooltip} from 'element-ui';
    import lang from 'element-ui/lib/locale/lang/en'
    import locale from 'element-ui/lib/locale'

    locale.use(lang);

    export default {
        name: 'PnlExplain',
        components: {'el-date-picker': DatePicker, 'el-tooltip': Tooltip},
        computed: {
            latestDate() {
                return this.$store.state.summary.latestDate;
            },
        },
        mounted() {
            const notify = this.$notify;
            axios.get('/api/pnlexplain/monthly')
                .then(response => {
                    this.explains = response.data;
                })
                .catch(error => notify.error(error));
        },
        methods: {
            onColumnClick(explain) {
                this.$router.push({name: 'pnldetail', params: {fromDate: explain.fromDate, toDate: explain.toDate}});
            },
            submit() {
                const args = {
                    fromDate: this.selectedRange[0],
                    toDate: this.selectedRange[1]
                };
                this.$router.push({name: 'pnldetail', params: args});
            }
        },
        data() {
            const self = this;
            return {
                explains: [],
                pickerOptions: {
                    shortcuts: [{
                        text: 'Last week',
                        onClick(picker) {
                            const end = new Date(self.latestDate);
                            const start = new Date();
                            start.setTime(end.getTime() - 3600 * 1000 * 24 * 7);
                            picker.$emit('pick', [start, end]);
                        }
                    }, {
                        text: 'Last month',
                        onClick(picker) {
                            const end = new Date(self.latestDate);
                            const start = new Date();
                            start.setTime(end.getTime());
                            start.setMonth(start.getMonth() - 1);
                            // start.setTime(end.getTime() - 3600 * 1000 * 24 * 30);
                            picker.$emit('pick', [start, end]);
                        }
                    }, {
                        text: 'Last 12 months',
                        onClick(picker) {
                            const end = new Date(self.latestDate);
                            const start = new Date();
                            start.setTime(end.getTime());
                            start.setMonth(start.getMonth() - 12);
                            picker.$emit('pick', [start, end]);
                        }
                    }, {
                        text: 'Year to date',
                        onClick(picker) {
                            const end = new Date(self.latestDate);
                            const start = new Date();
                            start.setTime(end.getTime());
                            start.setMonth(0);
                            start.setDate(1);
                            picker.$emit('pick', [start, end]);
                        }
                    }]
                },
                selectedRange: null,
            };

        }
    }
</script>

<style scoped>

</style>
