<template>
  <q-icon :name="matInfo">
    <q-tooltip>{{ tipText }}</q-tooltip>
  </q-icon>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {matInfo} from '@quasar/extras/material-icons';

const texts: Record<string, string> = {
  newActivityPnl: 'P&L generated by trades within the period, including both purchase at premium/discount and market price movements within the period',
  marketsPnl: 'P&L from positions as of from-date due to market price movements (excludes P&L from market movements of new trades done within the period)',
  fundOtherAccount: 'Source of funds when funding this account. By default, the funding accounts is defined when the account is set up',
  tradeChange: 'Enter the number of units or shares, followed by an id for the asset. This could be a currency (USD) a ticket (GOOG) or any other short string choice',
  tradePrice: 'Enter the price for a <em>single</em> unit of the asset or shares being purchased',
  tradeCommission: '(Optional) Enter any commission taken by your broker for this transaction',
  balOtherAccount: 'Select the account against which an adjustment will be booked to make this account balance. For one-off adjustments, Equity:Opening can be used. For current account, Expenses:General makes sense',
};

const props = defineProps<{
  tag?: string
  placement?: string
}>();

const tipText = computed((): string => {
  return texts[props.tag || ''] || `${props.tag} does not have help text defined`;
});
</script>

<style scoped>

</style>
