<template>
    <el-tooltip class="item" effect="dark" :content="tipText" placement="top-start">
        <i class="el-icon-info"></i>
    </el-tooltip>
</template>

<script lang="ts">
    import {Tooltip} from 'element-ui';
    import Vue from 'vue';

    const texts: Record<string, string> = {
        newActivityPnl: 'P&L generated by trades within the period, including both purchase at premium/discount and market price movements within the period',
        marketsPnl: 'P&L from positions as of from-date due to market price movements (excludes P&L from market movements of new trades done within the period)',
        fundOtherAccount: 'Source of funds when funding this account. By default, the funding accounts is defined when the account is set up',
        tradeChange: 'Enter the number of units or shares, followed by an id for the asset. This could be a currency (USD) a ticket (GOOG) or any other short string choice',
        tradePrice: 'Enter the price for a <em>single</em> unit of the asset or shares being purchased',
        tradeCommission: '(Optional) Enter any commission taken by your broker for this transaction',
        balOtherAccount: 'Select the account against which an adjustment will be booked to make this account balance. For one-off adjustments, Equity:Opening can be used. For current account, Expenses:General makes sense',
    };

    export default Vue.extend({
        name: 'HelpTip',
        components: {'el-tooltip': Tooltip},
        computed: {
            tipText(): string {
                return texts[this.tag] || `${this.tag} does not have help text defined`;
            }
        },
        props: {
            tag: {
                type: String,
            },
            placement: {
                type: String,
                default: 'top-start',
            }
        }
    });
</script>

<style scoped>

</style>