name: Web client CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node (24)
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'pnpm'
          cache-dependency-path: client/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test:unit:ci
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAINSTRACK }}'
          projectId: gainstrack
          target: poc
          entryPoint: ./client
