name: Web client CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node (20)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: NPM ci
        run: npm ci
      - name: Build
        run: npx quasar build
      - name: Test
        run: npx quasar test --unit jest
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0.6.0
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAINSTRACK }}'
          projectId: gainstrack
          target: poc
          entryPoint: ./client
